### ISSUE TITLE
关于bridgingskin插件的问题

### ISSUE THREAD

**Issue by IHIntary** [SakuraKoi/FileCloud#1]
载入后第一次可正常使用 待其生成玩家数据后 执行bskin指令会出现所谓内部错误 发现是其中玩家id前面的值比较怪异 请问是本该如此还是bug？

**Comment by SakuraKoi** [comment]
内部错误?后台应该有报错的日志，发一下方便分析原因
id前面的键是正常情况，上了丶混淆

**Comment by SakuraKoi** [comment]
Gson反序列化出错，疑似Bukkit自带的gson的问题
TODO: repackage gson
