### ISSUE TITLE
想问个问题

### ISSUE THREAD

**Issue by Astra-520** [SakuraKoi/FileCloud#2]
Sakurareport他没有bungeecord插件吗qwq

**Comment by SakuraKoi** [comment]
不需要，有两种举报通知同步模式
一种是通过bungeecord的数据广播频道发送
一种是通过数据库消息队列表发送
前者需要子服有至少1人在线才能在该子服接收消息，并且需要子服在同一bc下才能接收(bc套bc之类的会出问题)，后者无限制，但bc套bc会影响"在举报列表中点击直接跳到举报所在服务器"的功能
均不需要bungeecord侧安装额外插件(数据广播频道bc自带功能，数据库直接跟bc没关系了)

**Comment by SakuraKoi** [comment]
Close due to inactive, reopen if needed
